# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: ODIwOGZhNTdkYjIxMmMwZDVhNTUzZGM3YmI3NDNkOGRmZTM3ZGZiZTNmMjkzYTFiZGE2YjFkODE0YTU2YjNiZmQ4OGI2M2JhMzVlOWM4YzU2ODg2NTc0ODk4NWMzZjJhNWNhNjJjZjhjZWFlMDAwNjNhOWE2MjVjOGYzMGEzOTc=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
